app = 'docker-test'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 11434 
  force_https = false 
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '16gb'
  cpu_kind = 'performance'
  cpus = 8

[mounts]
  source="model_volume"
  destination="/root/.ollama"
