# fly.toml app configuration file generated for go-server-one on 2024-03-15T11:55:12-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'go-server-one'
primary_region = 'yyz'

[build]
  [build.args]
    GO_VERSION = '1.21.7'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
